apiVersion: v1
kind: Service
metadata:
  name: jai-service
spec:
  type: NodePort
  selector:
    myapp: jai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jai
  labels:
    myapp: jai
spec:
  replicas: 3
  selector:
    matchLabels:
      myapp: jai
  template:
    metadata:
      labels:
        myapp: jai
    spec:
      containers:
      - name: web
        image: jaibw/frozenyogurtshop
        ports:
        - containerPort: 80
