name: website06
on: push
jobs:
  building-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 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
          SONAR_TOKEN: squ_9830fa78c71b6fbf5df2e33defd339c769a461f2
          SONAR_HOST_URL: http://35.89.174.169:9000
